# .github/workflows/test.yml
name: Test VTL Engine

on:
  push:
    paths:
      - 'emulator/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'emulator/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: emulator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
