# .github/workflows/test.yml
name: Test VTL Engine

on:
  push:
    paths:
      - 'emulator/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'emulator/**'

jobs:
  test:
    name: Test Java VTL Processor
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: emulator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn clean test

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: emulator/target/surefire-reports/
          retention-days: 30
